name: waqas_brothers_eggs_merchants
description: "Inventory & billing app for Waqas Brothers Eggs Merchants."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.0
  go_router: ^17.0.1
  flutter_svg: ^2.2.3
  provider: ^6.1.5+1
  animations: ^2.1.1
  connectivity_plus: ^7.1.1
  shared_preferences: ^2.5.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
